from pathlib import Path

p = Path(r'O:\pc_pulse\PC-Pulse.html')
text = p.read_text(encoding='utf-8')
old = '''<section id="activity" class="view hidden"><div class="panel section"><div class="panel-title"><h2>Fájlműveletek</h2><button id="export">CSV export</button></div><div class="filters"><input id="search" placeholder="Fájlnév vagy útvonal keresése…" aria-label="Fájlnév vagy útvonal"><select id="programFilter" aria-label="Program"><option value="">Minden program</option></select><select id="userFilter" aria-label="Windows-fiók"><option value="">Minden fiók</option></select><select id="operation" aria-label="Művelet"><option value="">Minden művelet</option><option>Írás</option><option>Olvasás</option><option>Törlési hozzáférés</option></select><button id="reset">Szűrők törlése</button></div><div id="results" class="small" aria-live="polite"></div><div class="table-wrap"><table><thead><tr><th>Időpont</th><th>Windows-fiók</th><th>Program</th><th>Fájl</th><th>Művelet</th><th>Írt adat</th></tr></thead><tbody id="events"></tbody></table></div></div></section>'''
new = '''<section id="activity" class="view hidden"><div class="panel section"><div class="panel-title"><h2>Fájlműveletek</h2><div class="segmented"><button type="button" class="active" data-activity-mode="list">Lista</button><button type="button" data-activity-mode="chart">Grafikon</button></div><button id="export">CSV export</button></div><div class="filters"><input id="search" placeholder="Fájlnév vagy útvonal keresése…" aria-label="Fájlnév vagy útvonal"><select id="programFilter" aria-label="Program"><option value="">Minden program</option></select><select id="userFilter" aria-label="Windows-fiók"><option value="">Minden fiók</option></select><select id="operation" aria-label="Művelet"><option value="">Minden művelet</option><option>Írás</option><option>Olvasás</option><option>Törlési hozzáférés</option></select><button id="reset">Szűrők törlése</button></div><div id="results" class="small" aria-live="polite"></div><div id="chartRange" class="small"></div><div id="activityList"><div class="table-wrap"><table><thead><tr><th>Időpont</th><th>Windows-fiók</th><th>Program</th><th>Fájl</th><th>Művelet</th><th>Írt adat</th></tr></thead><tbody id="events"></tbody></table></div></div><div id="activityChart" class="hidden"></div></div></section>'''
if old not in text:
    raise SystemExit('old section not found')
text = text.replace(old, new)
old_style = '.hidden{display:none}.smallcaps{font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}'
new_style = '.hidden{display:none}.smallcaps{font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}.segmented{display:inline-flex;border:1px solid var(--line);border-radius:8px;overflow:hidden}.segmented button{border:none;border-radius:0;padding:8px 12px;background:transparent}.segmented button.active{background:#1b2d3d;color:var(--mint)}#activityChart.hidden,#activityList.hidden{display:none}.chart-bars{display:flex;align-items:flex-end;gap:10px;min-height:220px;padding:12px 0 6px;overflow:auto}.chart-bar-wrap{display:flex;flex-direction:column;justify-content:flex-end;align-items:center;gap:6px;min-width:28px}.chart-bar{width:100%;min-height:8px;border-radius:8px 8px 0 0;background:linear-gradient(180deg,#4ce0bb,#2ca58a)}.chart-bar-wrap span{font-size:11px;color:var(--muted)}.empty-chart{padding:24px;color:var(--muted)}'
if old_style not in text:
    raise SystemExit('style anchor not found')
text = text.replace(old_style, new_style)
old_script = '''function activeFilters(){const q=$('search').value.trim();return{path:q,program:$('programFilter').value,operation:$('operation').value}};
function filtered(){const {path,program,operation}=activeFilters();const q=path.toLocaleLowerCase();return events.filter(e=>(!q||e.path.toLocaleLowerCase().includes(q))&&(!program||e.program===program)&&(!operation||e.operation===operation))}
function render(){const list=filtered();$('results').textContent=`${list.length} esemény a betöltött ${events.length}-ből · legfeljebb 5000 legfrissebb esemény · utolsó ${periodLabel()}`;$('events').replaceChildren();list.forEach(e=>{const tr=document.createElement('tr');[date(e.time),e.user,e.program,e.path,e.operation,'—'].forEach((v,i)=>{const td=document.createElement('td');if(i===3)td.className='path';td.textContent=v;tr.append(td)});$('events').append(tr)});if(!list.length)$('events').innerHTML='<tr><td colspan="6" class="empty">Nincs rögzített, a szűrésnek megfelelő esemény. Ellenőrizd a gyűjtő állapotát és az audit beállítását.</td></tr>'}
function reset(){$('search').value='';$('programFilter').value='';$('operation').value='';refreshEvents();render()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)show(b.dataset.view);if(b.dataset.program){reset();$('programFilter').value=b.dataset.program;refreshEvents();show('activity')}if(b.dataset.folder){reset();$('search').value=b.dataset.folder;refreshEvents();show('activity')}});
$('reset').onclick=reset;['search','programFilter','operation'].forEach(id=>$(id).addEventListener('input',refreshEvents));
$('export').onclick=()=>{const rows=[['Időpont','Windows-fiók','Program','Fájl','Művelet'],...filtered().map(e=>[date(e.time),e.user,e.program,e.path,e.operation])];const csv='\ufeff'+rows.map(r=>r.map(v=>"\""+String(/^[=+@-]/.test(v)?"'"+v:v).replaceAll('"','""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='PC-Pulse-activity.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};'''
new_script = '''function activeFilters(){const q=$('search').value.trim();return{path:q,program:$('programFilter').value,user:$('userFilter').value,operation:$('operation').value}};
function filtered(){const {path,program,user,operation}=activeFilters();const q=path.toLocaleLowerCase();return events.filter(e=>(!q||e.path.toLocaleLowerCase().includes(q))&&(!program||e.program===program)&&(!user||e.user===user)&&(!operation||e.operation===operation))}
function renderChart(){const chart=(data&&data.chart&&data.chart.buckets)?data.chart.buckets:[];const host=$('activityChart');host.innerHTML='';if(!chart.length){host.innerHTML='<p class="empty-chart">Nincs a szűrésnek megfelelő esemény a kiválasztott időszakban.</p>';return}const max=Math.max(1,...chart.map(b=>b.count));const width=Math.max(26,Math.min(70,Math.round(1100/chart.length)));const label=(data&&data.chart&&data.chart.bucketLabel)?data.chart.bucketLabel:'1 óra';$('chartRange').textContent='Időbontás: '+label;host.innerHTML='<div class="chart-bars">'+chart.map(b=>{const start=new Date(b.start*1000);const end=new Date(b.end*1000);const title=start.toLocaleString('hu-HU')+' – '+end.toLocaleString('hu-HU')+': '+b.count+' esemény';const height=Math.max(8,(b.count/max)*100);const tick=chart.length>12?start.toLocaleDateString('hu-HU',{month:'short',day:'numeric'}):start.toLocaleTimeString('hu-HU',{hour:'2-digit',minute:'2-digit'});return '<div class="chart-bar-wrap" title="'+title+'" style="width:'+width+'px"><div class="chart-bar" style="height:'+height+'%"></div><span>'+tick+'</span></div>'}).join('')+'</div>'}
function render(){const list=filtered();$('results').textContent=`${list.length} esemény a betöltött ${events.length}-ből · legfeljebb 5000 legfrissebb esemény · utolsó ${periodLabel()}`;$('events').replaceChildren();list.forEach(e=>{const tr=document.createElement('tr');[date(e.time),e.user,e.program,e.path,e.operation,'—'].forEach((v,i)=>{const td=document.createElement('td');if(i===3)td.className='path';td.textContent=v;tr.append(td)});$('events').append(tr)});if(!list.length)$('events').innerHTML='<tr><td colspan="6" class="empty">Nincs rögzített, a szűrésnek megfelelő esemény. Ellenőrizd a gyűjtő állapotát és az audit beállítását.</td></tr>';renderChart()}
function reset(){$('search').value='';$('programFilter').value='';$('userFilter').value='';$('operation').value='';refreshEvents();render()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)show(b.dataset.view);if(b.dataset.program){reset();$('programFilter').value=b.dataset.program;refreshEvents();show('activity')}if(b.dataset.folder){reset();$('search').value=b.dataset.folder;refreshEvents();show('activity')}if(b.dataset.activityMode){const mode=b.dataset.activityMode;document.querySelectorAll('[data-activity-mode]').forEach(btn=>btn.classList.toggle('active',btn===b));document.getElementById('activityList').classList.toggle('hidden',mode!=='list');document.getElementById('activityChart').classList.toggle('hidden',mode!=='chart');}});
$('reset').onclick=reset;['search','programFilter','userFilter','operation'].forEach(id=>$(id).addEventListener('input',refreshEvents));
$('export').onclick=()=>{const rows=[['Időpont','Windows-fiók','Program','Fájl','Művelet'],...filtered().map(e=>[date(e.time),e.user,e.program,e.path,e.operation])];const csv='\ufeff'+rows.map(r=>r.map(v=>"\""+String(/^[=+@-]/.test(v)?"'"+v:v).replaceAll('"','""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='PC-Pulse-activity.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};'''
if old_script not in text:
    raise SystemExit('old script block not found')
text = text.replace(old_script, new_script)
p.write_text(text, encoding='utf-8')
print('patched html')
